# coding: utf-8


"""
IGNORE:
    Nutanix Prism Versioned APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
IGNORE
"""
import pprint
import json
import ast
import re  # noqa: F401

import six

"""
IGNORE:
NOTE: This class is auto generated by the swagger code generator program.

Do not edit the class manually.
IGNORE
"""

class ResourceType(object):

    """
    allowed enum values
    """
    _UNKNOWN = "$UNKNOWN"
    _REDACTED = "$REDACTED"
    VM = "VM"
    IMAGE = "IMAGE"
    SUBNET = "SUBNET"
    CLUSTER = "CLUSTER"
    HOST = "HOST"
    REPORT = "REPORT"
    MARKETPLACE_ITEM = "MARKETPLACE_ITEM"
    BLUEPRINT = "BLUEPRINT"
    APP = "APP"
    VOLUMEGROUP = "VOLUMEGROUP"
    IMAGE_PLACEMENT_POLICY = "IMAGE_PLACEMENT_POLICY"
    NETWORK_SECURITY_POLICY = "NETWORK_SECURITY_POLICY"
    NETWORK_SECURITY_RULE = "NETWORK_SECURITY_RULE"
    VM_HOST_AFFINITY_POLICY = "VM_HOST_AFFINITY_POLICY"
    QOS_POLICY = "QOS_POLICY"
    NGT_POLICY = "NGT_POLICY"
    PROTECTION_RULE = "PROTECTION_RULE"
    ACCESS_CONTROL_POLICY = "ACCESS_CONTROL_POLICY"
    STORAGE_POLICY = "STORAGE_POLICY"
    IMAGE_RATE_LIMIT = "IMAGE_RATE_LIMIT"
    RECOVERY_PLAN = "RECOVERY_PLAN"


    def __init__(self, *args, **kwargs):  # noqa: E501
        """ResourceType - a model defined in Swagger
            \nAn enum denoting the type of the resources associated.<br> The following entity types are currently supported by the service: - VM - IMAGE - SUBNET - CLUSTER - HOST - REPORT - MARKETPLACE_ITEM - BLUEPRINT - APP 
        """
        self.discriminator = None
        # populate hidden vars if not empty
        self._populate_hidden_vars(kwargs)

    def _initialize_object_type(self):
        return 'prism.v4.config.ResourceType'

    def _initialize_fq_object_type(self):
        return 'prism.v4.r0.a1.config.ResourceType'

    def _populate_hidden_vars(self, kwargs):
        if "_reserved" in kwargs and kwargs["_reserved"] is not None:
            self.__reserved = kwargs["_reserved"]
        elif "_reserved" in self.attribute_map and self.attribute_map["_reserved"] in kwargs and kwargs[self.attribute_map["_reserved"]] is not None:
            self.__reserved = kwargs[self.attribute_map["_reserved"]]
        else :
            self.__reserved = {"$fqObjectType": self._initialize_fq_object_type()}
        if "_unknown_fields" in kwargs and kwargs["_unknown_fields"] is not None:
            self.__unknown_fields = kwargs["_unknown_fields"]
        elif "_unknown_fields" in self.attribute_map and self.attribute_map["_unknown_fields"] in kwargs and kwargs[self.attribute_map["_unknown_fields"]] is not None:
            self.__unknown_fields = kwargs[self.attribute_map["_unknown_fields"]]
        else :
            self.__unknown_fields = {}
        if "_object_type" in kwargs and kwargs["_object_type"] is not None:
            self.__object_type = kwargs["_object_type"]
        elif "_object_type" in self.attribute_map and self.attribute_map["_object_type"] in kwargs and kwargs[self.attribute_map["_object_type"]] is not None:
            self.__object_type = kwargs[self.attribute_map["_object_type"]]
        else:
            self.__object_type = self._initialize_object_type()

    def get_object_type(self):
        return self.__object_type

    def get_reserved(self):
        return self.__reserved

    def get_unknown_fields(self):
        return self.__unknown_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, attr_type in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResourceType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other

