# coding: utf-8


"""
    Storage APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 16.1.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
import pprint
import re  # noqa: F401

import six
from swagger_client.Ntnx.common.v1.config.FQDN import FQDN  # noqa: F401,E501
from swagger_client.Ntnx.common.v1.config.IPv4Address import IPv4Address  # noqa: F401,E501
from swagger_client.Ntnx.common.v1.config.IPv6Address import IPv6Address  # noqa: F401,E501


class IPAddressOrFQDN(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ipv4': 'common.v1.config.IPv4Address',
        'ipv6': 'common.v1.config.IPv6Address',
        'fqdn': 'common.v1.config.FQDN',
        '_reserved': 'dict(str, object)',
        '_object_type': 'str',
        '_unknown_fields': 'dict(str, object)',
    }

    attribute_map = {
        'ipv4': 'ipv4',
        'ipv6': 'ipv6',
        'fqdn': 'fqdn',
        '_reserved': '$reserved',
        '_object_type': '$objectType',
        '_unknown_fields': '$unknownFields',
    }


    def __init__(self, ipv4=None, ipv6=None, fqdn=None, *args, **kwargs):  # noqa: E501
        """IPAddressOrFQDN - a model defined in Swagger"""  # noqa: E501
        self._ipv4 = None
        self._ipv6 = None
        self._fqdn = None
        self.discriminator = None
        if ipv4 is not None:
            self._ipv4 = ipv4
        if ipv6 is not None:
            self._ipv6 = ipv6
        if fqdn is not None:
            self._fqdn = fqdn
        self.__reserved = {"$fqObjectType": self._initialize_fq_object_type()}
        self.__unknown_fields = {}
        self.__object_type = self._initialize_object_type()

    def _initialize_object_type(self):
        return 'common.v1.config.IPAddressOrFQDN'

    def _initialize_fq_object_type(self):
        return 'common.v1.r0.a3.config.IPAddressOrFQDN'

    def get_object_type(self):
        return self.__object_type

    def get_reserved(self):
        return self.__reserved

    def get_unknown_fields(self):
        return self.__unknown_fields

    @property
    def ipv4(self):
        """Gets the ipv4 of this IPAddressOrFQDN.  # noqa: E501


        :return: The ipv4 of this IPAddressOrFQDN.  # noqa: E501
        :rtype: common.v1.config.IPv4Address
        """
        return self._ipv4

    @ipv4.setter
    def ipv4(self, ipv4):
        """Sets the ipv4 of this IPAddressOrFQDN.


        :param ipv4: The ipv4 of this IPAddressOrFQDN.  # noqa: E501
        :type: common.v1.config.IPv4Address
        """

        self._ipv4 = ipv4

    @property
    def ipv6(self):
        """Gets the ipv6 of this IPAddressOrFQDN.  # noqa: E501


        :return: The ipv6 of this IPAddressOrFQDN.  # noqa: E501
        :rtype: common.v1.config.IPv6Address
        """
        return self._ipv6

    @ipv6.setter
    def ipv6(self, ipv6):
        """Sets the ipv6 of this IPAddressOrFQDN.


        :param ipv6: The ipv6 of this IPAddressOrFQDN.  # noqa: E501
        :type: common.v1.config.IPv6Address
        """

        self._ipv6 = ipv6

    @property
    def fqdn(self):
        """Gets the fqdn of this IPAddressOrFQDN.  # noqa: E501


        :return: The fqdn of this IPAddressOrFQDN.  # noqa: E501
        :rtype: common.v1.config.FQDN
        """
        return self._fqdn

    @fqdn.setter
    def fqdn(self, fqdn):
        """Sets the fqdn of this IPAddressOrFQDN.


        :param fqdn: The fqdn of this IPAddressOrFQDN.  # noqa: E501
        :type: common.v1.config.FQDN
        """

        self._fqdn = fqdn

    @property
    def _reserved(self):
        """Gets the _reserved of this IPAddressOrFQDN.  # noqa: E501


        :return: The _reserved of this IPAddressOrFQDN.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self.__reserved

    @property
    def _object_type(self):
        """Gets the _object_type of this IPAddressOrFQDN.  # noqa: E501


        :return: The _object_type of this IPAddressOrFQDN.  # noqa: E501
        :rtype: str
        """
        return self.__object_type

    @property
    def _unknown_fields(self):
        """Gets the _unknown_fields of this IPAddressOrFQDN.  # noqa: E501


        :return: The _unknown_fields of this IPAddressOrFQDN.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self.__unknown_fields

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IPAddressOrFQDN, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IPAddressOrFQDN):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other

    def has_ipv4(self):
        """Returns true if ipv4 has non-none value"""
        return self._ipv4 is None
    def has_ipv6(self):
        """Returns true if ipv6 has non-none value"""
        return self._ipv6 is None
    def has_fqdn(self):
        """Returns true if fqdn has non-none value"""
        return self._fqdn is None
    def is_valid(self):
        """Returns true if any one of the attributes has non-none value"""
        return self.has_ipv4() or self.has_ipv6() or self.has_fqdn()
