# coding: utf-8


"""
IGNORE:
    Nutanix Prism Versioned APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
IGNORE
"""
from __future__ import absolute_import

import unittest

import prism_client
from api.categories_api import CategoriesApi  # noqa: E501
from prism_client.rest import ApiException


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self):
        self.api = api.categories_api.CategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_category(self):
        """Test case for create_category

        Creates category   # noqa: E501
        """
        pass

    def test_delete_category_by_ext_id(self):
        """Test case for delete_category_by_ext_id

        Deletes category   # noqa: E501
        """
        pass

    def test_get_all_categories(self):
        """Test case for get_all_categories

        Get category list   # noqa: E501
        """
        pass

    def test_get_associations_for_category(self):
        """Test case for get_associations_for_category

        Get category entity references   # noqa: E501
        """
        pass

    def test_get_category_by_ext_id(self):
        """Test case for get_category_by_ext_id

        Get category by extId   # noqa: E501
        """
        pass

    def test_update_category(self):
        """Test case for update_category

        Update category   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
