# coding: utf-8


"""
IGNORE:
    Nutanix Prism Versioned APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
IGNORE
"""
from __future__ import absolute_import

import unittest

import prism_client
from api.task_api import TaskApi  # noqa: E501
from prism_client.rest import ApiException


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self):
        self.api = api.task_api.TaskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_task_cancel(self):
        """Test case for task_cancel

        """
        pass

    def test_task_get(self):
        """Test case for task_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
