# coding: utf-8


"""
    Storage APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 16.1.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
from __future__ import absolute_import

import unittest

import swagger_client
from api.volume_group_api import VolumeGroupApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVolumeGroupApi(unittest.TestCase):
    """VolumeGroupApi unit test stubs"""

    def setUp(self):
        self.api = api.volume_group_api.VolumeGroupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_associate_category(self):
        """Test case for associate_category

        """
        pass

    def test_attach_iscsi_client(self):
        """Test case for attach_iscsi_client

        """
        pass

    def test_attach_vm(self):
        """Test case for attach_vm

        """
        pass

    def test_create_volume_disk(self):
        """Test case for create_volume_disk

        """
        pass

    def test_create_volume_group(self):
        """Test case for create_volume_group

        """
        pass

    def test_delete_volume_disk(self):
        """Test case for delete_volume_disk

        """
        pass

    def test_delete_volume_group_by_id(self):
        """Test case for delete_volume_group_by_id

        """
        pass

    def test_detach_iscsi_client(self):
        """Test case for detach_iscsi_client

        """
        pass

    def test_detach_vm(self):
        """Test case for detach_vm

        """
        pass

    def test_disassociate_category(self):
        """Test case for disassociate_category

        """
        pass

    def test_get_category_associations(self):
        """Test case for get_category_associations

        """
        pass

    def test_get_external_attachments(self):
        """Test case for get_external_attachments

        """
        pass

    def test_get_vm_attachments(self):
        """Test case for get_vm_attachments

        """
        pass

    def test_get_volume_disk_by_id(self):
        """Test case for get_volume_disk_by_id

        """
        pass

    def test_get_volume_disks(self):
        """Test case for get_volume_disks

        """
        pass

    def test_get_volume_group_by_id(self):
        """Test case for get_volume_group_by_id

        """
        pass

    def test_get_volume_groups(self):
        """Test case for get_volume_groups

        """
        pass

    def test_migrate_volume_group(self):
        """Test case for migrate_volume_group

        """
        pass

    def test_update_volume_disk(self):
        """Test case for update_volume_disk

        """
        pass

    def test_update_volume_group_by_id(self):
        """Test case for update_volume_group_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
