# coding: utf-8


"""
    Storage APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 16.1.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
from __future__ import absolute_import

import unittest

import swagger_client
from api.iscsi_client_api import IscsiClientApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIscsiClientApi(unittest.TestCase):
    """IscsiClientApi unit test stubs"""

    def setUp(self):
        self.api = api.iscsi_client_api.IscsiClientApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_iscsi_client_by_id(self):
        """Test case for get_iscsi_client_by_id

        """
        pass

    def test_get_iscsi_clients(self):
        """Test case for get_iscsi_clients

        """
        pass

    def test_update_iscsi_client_by_id(self):
        """Test case for update_iscsi_client_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
